title: Data Science Projects
email: karsonleperi@gmail.com
theme: minima

#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your site's footer.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: KarsonLeperi

# Build settings
#markdown: kramdown
