title: Karson Leperi
show_downloads: false
theme: minima

author:
  name: Karson Leperi
  email: karsonleperi@gmail.com
description:
  A repository for all the data science projects I am working on.

social_links:
 - title: Minima Theme repository at GitHub
   icon: github
   url: "https://github.com/jekyll/minima"
